# Generated by Django 6.0.6 on 2026-06-19 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CVSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('headline', 'Headline'), ('about', 'About'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('certifications', 'Licenses & Certifications'), ('projects', 'Projects'), ('publications', 'Publications'), ('patents', 'Patents'), ('courses', 'Courses'), ('honors', 'Honors & Awards'), ('volunteer', 'Volunteer Experience'), ('languages', 'Languages'), ('organizations', 'Organizations'), ('featured', 'Featured'), ('recommendations', 'Recommendations')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cv.cv')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('cv', 'section_type')},
            },
        ),
        migrations.CreateModel(
            name='CVEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cv.cvsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
