# Generated by Django 6.0.6 on 2026-06-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvsection',
            name='section_type',
            field=models.CharField(choices=[('contact', 'Contact'), ('headline', 'Headline'), ('about', 'About'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('certifications', 'Licenses & Certifications'), ('projects', 'Projects'), ('publications', 'Publications'), ('patents', 'Patents'), ('courses', 'Courses'), ('honors', 'Honors & Awards'), ('volunteer', 'Volunteer Experience'), ('languages', 'Languages'), ('organizations', 'Organizations'), ('featured', 'Featured'), ('recommendations', 'Recommendations')], max_length=50),
        ),
    ]
