# Generated by Django 6.0.6 on 2026-06-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_posting_url',
            field=models.URLField(blank=True),
        ),
    ]
