# Generated by Django 6.0.6 on 2026-06-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplication_job_posting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_url',
            field=models.URLField(blank=True),
        ),
    ]
