# Generated by Django 6.0.6 on 2026-06-19 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_posting', models.TextField()),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('position_title', models.CharField(blank=True, max_length=200)),
                ('generation_method', models.CharField(choices=[('ai_generated', 'AI Generated'), ('copied', 'Copied')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.customresume')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('headline', 'Headline'), ('about', 'About'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('certifications', 'Licenses & Certifications'), ('projects', 'Projects'), ('publications', 'Publications'), ('patents', 'Patents'), ('courses', 'Courses'), ('honors', 'Honors & Awards'), ('volunteer', 'Volunteer Experience'), ('languages', 'Languages'), ('organizations', 'Organizations'), ('featured', 'Featured'), ('recommendations', 'Recommendations')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('custom_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resumes.customresume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopicalResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Description of the job type this resume targets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topical_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='customresume',
            name='topical_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_resumes', to='resumes.topicalresume'),
        ),
        migrations.CreateModel(
            name='TopicalResumeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('cv_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topical_entries', to='cv.cventry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomResumeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='resumes.customresumesection')),
                ('topical_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.topicalresumeentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopicalResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('headline', 'Headline'), ('about', 'About'), ('experience', 'Experience'), ('education', 'Education'), ('skills', 'Skills'), ('certifications', 'Licenses & Certifications'), ('projects', 'Projects'), ('publications', 'Publications'), ('patents', 'Patents'), ('courses', 'Courses'), ('honors', 'Honors & Awards'), ('volunteer', 'Volunteer Experience'), ('languages', 'Languages'), ('organizations', 'Organizations'), ('featured', 'Featured'), ('recommendations', 'Recommendations')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topical_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resumes.topicalresume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='topicalresumeentry',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='resumes.topicalresumesection'),
        ),
    ]
