# Generated by Django 6.0.6 on 2026-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.CharField(choices=[('verdigris', 'Verdigris'), ('ember', 'Ember'), ('slate', 'Slate')], default='verdigris', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site theme',
                'verbose_name_plural': 'Site theme',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mode',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
